feat: add ukrainian localization
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #386
Opened 2023-09-06 15:02 UTC by shegols

2023-09-10 21:19 UTC, LewisSaber requested changes
Its already very late, I reviewed first 350 lines, submiting in case google erase it all if I close it, will continue later

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.appliedenergistics2.HoldShiftForTooltip=Утримуйте клавішу для розширеної підказки
Утримуйте клавішу Shift для розширеної підказки

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.Stash=Зберігати предмети
"Зберегти прежмети"

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.Substitutions=Заміни рудного дикту
"Заміни Ore-Dict" I don`t think u really want to translate this word

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.SubstitutionsDescDisabled=Запобігає підміні вхідних компонентів.
Запобігає заміні вхідних компонентів

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.BeSubstitutionsDescEnabled=Дозвольте створення як заміну вхідних компонентів.
"Дозволяє створення заміни вхідних компонентів"

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.BeSubstitutionsDescDisabled=Запобігає створенню як підміні вхідних компонентів. Якщо всі доступні для інгредієнта шаблони вимкнено для заміни, симулятор створення буд
"Забороняє створення заміни вхідних компонентів." Second sentence is fine

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.PatternSlotConfigInfo=Перемкнути режим слота шаблону на "між" (16 -> 4) та (4 -> 16)
Перемкнути режим створення шаблону між (16 -> 4) та (4 -> 16)

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.appliedenergistics2.StoredStacks=Накопічені стоси
"накопичені стеки"

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.TransferToStorageCell=Передати дані до комірки зберігання
"Передати дані до диску зберігання"

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.MatterBalls=Конденсувати в м'ячики матерії\n%s за предмет
"Конденсувати в кулі матерії\n%s за предмет", to keep consistency with matter ball translation

2023-09-10 21:19 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.SearchMode_NEIAuto=NEI Synchronized Auto
Синхронізований авто пошук NEI

2023-09-19 08:03 UTC, LewisSaber requested changes

2023-09-19 08:03 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemMaterial.SiliconPrint.name=Друкований кремній
I dont think "Друкований" fits there, my idea is "штампований", but maybe you have better idea

2023-09-19 08:13 UTC, LewisSaber commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.Substitutions=Заміни рудного дикту
or "Заміни по рудному словнику"

2023-10-14 02:22 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.EmitLevelAbove=Випромінювати сигнал, коли рівні вищі або дорівнюють ліміту.
"рівні" -> "рівень"

2023-10-14 02:29 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +gui.tooltips.appliedenergistics2.CraftEither=Використовувати складені предмети або створити під час експорту.
"складені" -> "збережені" for both

2023-10-14 02:45 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemMaterial.CardAdvancedBlocking.name=Картка просунутого блокування
"картка" -> "карта"
or replace "карта" -> "картка" in other lines, i think should use same word for each

2023-10-14 02:47 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemMaterial.IronDust.name=Залізний пил
"пил" -> "порошок"

2023-10-14 02:48 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemMaterial.SkyDust.name=Пил небесного каменю
"пил" -> "порошок"

2023-10-14 02:50 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemPart.CableAnchor.name=Кабельний якір
"якір" -> "анкер"

2023-10-14 02:51 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ItemPart.StorageMonitor.name=ME Монітор зберігання
"збергігання" -> "сховища"

2023-10-14 02:54 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +item.appliedenergistics2.ToolReplicatorCard.name=Dev.ReplicatorCard
missing translation

2023-10-14 02:56 UTC, lordIcocain commented on src/main/resources/assets/appliedenergistics2/lang/uk_UA.lang
> +stat.ae2.ItemsInserted=Складено предметів в ME-Сховище
"Складено" -> "Збережено"

2023-10-30 07:21 UTC, merged