Fix index out of bounds error when trying to craft.
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #480
Opened 2024-02-28 04:29 UTC by koiNoCirculation

![9aedf08a7d68ee4dbf3352a8b4f8b440](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/57739338/e3b9066f-d373-4ee2-bac6-d81b6cadd998)
Error message in console.
When submitting a craft task, the server kicks me out.

2024-03-01 18:16 UTC, OneEyeMaker requested changes

2024-03-01 18:16 UTC, OneEyeMaker commented on src/main/java/appeng/container/AEBaseContainer.java
> +        }
For brevity:
```suggestion
        final int inventorySize = this.inventorySlots.size();
        if (slotA < 0 || slotA >= inventorySize || slotB < 0 || slotB >= inventorySize) {
            return;
        }
        final Slot a = this.getSlot(slotA);
        final Slot b = this.getSlot(slotB);
```

2024-03-03 08:43 UTC, Dream-Master commented
@koiNoCirculation

2024-03-04 15:05 UTC, OneEyeMaker approved these changes

2024-03-04 15:50 UTC, merged