Add halving to the double button and optimize the code
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #483
Opened 2024-03-02 12:58 UTC by wohaopa

2024-03-02 13:10 UTC, wohaopa commented
Don't worry, these commits are forward compatible. For example: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/470

2024-03-02 13:31 UTC, wohaopa commented
Now, I use the same coding rules as for PR 470

2024-03-04 19:24 UTC, Dream-Master commented
@wohaopa can you rebase your pr against kubas branch because i get merge conflicts whn try to build a dev test version

2024-03-05 03:41 UTC, wohaopa commented
Now, this PR has only been optimized for code. Maybe I will open a new PR in the future to complete other work I wanted to do before.

2024-03-05 07:21 UTC, OneEyeMaker requested changes
Nice job!
There are few nitpicks I want to be addressed.
Also it would be great if you continue this project in AE2FC.

2024-03-05 07:21 UTC, OneEyeMaker commented on src/main/java/appeng/client/gui/implementations/GuiAmount.java
> +        final int d = AEConfig.instance.craftItemsByStackAmounts(3);
Please, make sure that correct config is used and make this base class compatible with https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/192 (to allow changing config).

2024-03-05 07:21 UTC, OneEyeMaker commented on src/main/java/appeng/client/gui/implementations/GuiPatternMulti.java
> +            // this.symbolSwitch.set(resultI >= 0 ? ActionItems.MULTIPLY : ActionItems.DIVIDE);
Please, remove all commented code to prevent future confusions.

2024-03-05 11:13 UTC, Dream-Master commented
@wohaopa now you need to run spotless

2024-03-05 12:29 UTC, OneEyeMaker approved these changes

2024-03-05 16:33 UTC, merged