The terminal style button in some GUIs is independent of others
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #488
Opened 2024-03-10 15:53 UTC by claimg

In craft confirmation and status gui, the terminal style button depends on the button specified in the terminal and this is not always convenient. I suggest to keep the state of the button in the confirmation and status gui separate from the state of other terminal style buttons.

2024-03-10 22:47 UTC, Laiff commented
Make a separate logic specially for this screen looks very weird, I think this PR isn't relevant to release

2024-03-10 22:49 UTC, Laiff requested changes
need to be discussed

2024-03-11 10:31 UTC, Laiff requested changes

2024-03-11 10:31 UTC, Laiff commented on src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java
> +        this.tallMode = AEConfig.instance.getConfigManager().getSetting(Settings.CRAFT_GUI_STYLE) == TerminalStyle.TALL;
Let's reuse already existed setting here

2024-03-11 10:31 UTC, Laiff commented on src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java
> +                        .putSetting(Settings.CRAFT_GUI_STYLE, tallMode ? TerminalStyle.TALL : TerminalStyle.SMALL);
Save `Settings.TERMINAL_STYLE` setting here, also check terminals in AE2FC to add similar logic

2024-03-11 13:05 UTC, claimg commented
These changes are different from the theme of this PR, so I think it's worth to close the PR or wait for more time, maybe someone has an idea how to satisfy people who want a small terminal and a big craft confirm gui.

2024-03-13 04:23 UTC, MCTBL commented
So this pr  just change some code, without any appearance change? Or just I haven't find it?

2024-03-13 09:17 UTC, claimg commented
> So this pr just change some code, without any appearance change? Or just I haven't find it?

The original point was to separate the state of the terminal style buttons, because some people want a small terminal and tall craft confirm gui without pressing extra buttons. I guess if the reviewer didn't like the idea, I'll close this PR.

2024-03-13 11:27 UTC, closed without merging