swap the remaining time to how long has been
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #491
Opened 2024-03-12 06:29 UTC by MCTBL

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/d820bc82-abc7-4a98-b57a-57979497d5b6

but if restart the game it will recount the time now
close: #407

2024-03-12 16:18 UTC, OneEyeMaker requested changes

2024-03-12 16:18 UTC, OneEyeMaker commented on src/main/java/appeng/client/gui/implementations/GuiCraftingCPU.java
>              final long etaInMilliseconds = TimeUnit.MILLISECONDS
nit: rename variables to prevent confusion.

2024-03-12 16:18 UTC, OneEyeMaker commented on src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java
>                  this.prepareElapsedTime();
Is this call necessary? If not, remove it and properly deprecate all related fields

2024-03-12 17:17 UTC, MCTBL commented on src/main/java/appeng/client/gui/implementations/GuiCraftingCPU.java
> +            // If title is empty, don't show that ' - '
| have name | no name |
| :-: | :-: |
| ![CP_AE 7$YCKI CBOJQ(N7YA](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/aabfcd24-b85f-41d5-aa7b-7078d2a09246) | ![VO A_SC{ QLKIM1DI7MS7TX](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/cf35f6e0-d3bc-4fe1-87f6-0b218428aafe) |

2024-03-12 17:19 UTC, MCTBL commented on src/main/java/appeng/container/implementations/CraftingCPUStatus.java
> +        return Platform.formatByteDouble(getStorage());
| befroe | after |
| :-: | :-: |
| ![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/514fb310-3e2c-474f-bad7-c5fd82e0e965) | ![XZ{T$3~VX4G}T$%E50HEVS8](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/0626fade-0992-46c2-984f-2b4f0ee3bed7) |

2024-03-12 17:37 UTC, OneEyeMaker requested changes
After deeper investigation I found that there's no need in removing existing logic; even more  - there's no need in new methods. `CraftingCPUCluster` already counts elapsed time (`elapsedTime` field) for internal calculations. You need to return to original logic and *just display it*. 

Correct me if I'm mistaken.

2024-03-13 02:31 UTC, MCTBL commented on src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java
> +        final String byteUsed = Platform.formatByteDouble(BytesUsed);
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/749e1dfa-d5ce-44ee-9e75-dc3bb591f0e6)

2024-03-13 02:32 UTC, MCTBL commented on src/main/java/appeng/client/gui/implementations/GuiCraftConfirm.java
> +                            + Platform.formatByteDouble(this.ccc.getCpuAvailableBytes())
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/23748999-2f2b-4344-acf7-917495af2b67)

2024-03-13 08:06 UTC, OneEyeMaker approved these changes
Looks good!
Right now I can't run this branch in full pack. So please check that method renaming doesn't break any addons.

2024-03-13 08:19 UTC, merged