Remove storage cell blinking code
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #526
Opened 2024-07-15 20:07 UTC by tth05

Completely remove old cell blinking code (there is no rendering code for this anymore). This also gets rid of the DriveWatcher class which spammed block updates on almost every insert and extract. The ME Drive/Chest now just update themselves if their state changed every 15 ticks.

2024-07-15 20:08 UTC, Caedis commented
but mah blinkenlights

2024-07-15 20:12 UTC, Pelotrio commented
> but mah blinkenlights

There never were any

2024-07-15 20:17 UTC, S4mpsa commented
tth coming in with another optimization pass?

2024-07-16 00:30 UTC, tth05 commented
> tth coming in with another optimization pass?

I knew about this for a while but haven't gotten to it yet. Maybe I'll look at more stuff

2024-07-19 19:42 UTC, mitchej123 approved these changes
seems fine - yolo

2024-07-19 20:44 UTC, mitchej123 requested changes

2024-07-19 20:44 UTC, mitchej123 commented on src/main/java/appeng/api/storage/ICellContainer.java
> -    void blinkCell(int slot);
hmm, now that I think about this, probably best to make this a default that does nothing as to keep public API compatability

2024-07-19 20:44 UTC, mitchej123 commented on src/main/java/appeng/api/implementations/tiles/IChestOrDrive.java
> -    boolean isCellBlinking(int slot);
same here; mark it as deprecated but put in a default method for backwards compat

2024-07-19 23:18 UTC, mitchej123 approved these changes

2024-07-20 00:54 UTC, merged