add different color for cell inside drive and chest
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #576
Opened 2024-09-09 17:34 UTC by MCTBL

Now different type of cell inside drive and me chest will show different color

Item is `0xa8a8a8`
Fluid is `0x3689b3`
Essentia is `0xaaaaff`

---

![{ _K%{Q9LQBYT92%2S L9V1](https://github.com/user-attachments/assets/bcd6749a-353b-4c07-b934-fc44fca77770)
![QR9A 8V`TIM VPJYSN8R8 S](https://github.com/user-attachments/assets/8aff7107-9a72-496a-9e38-f2405bc8d083)

2024-09-10 02:58 UTC, MCTBL commented
| inside | outside |
| :-: | :-:|
| ![image](https://github.com/user-attachments/assets/98c2bcd2-788e-4c61-926e-aeef41e5fc34) | ![image](https://github.com/user-attachments/assets/180bd1c8-8616-4837-be7d-bda88c9601b4) |

2024-09-12 16:06 UTC, OneEyeMaker requested changes

2024-09-12 16:06 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileChest.java
> +            newType |= (this.getCellType(x) << (3 * x));
Since there are only 3 cell types, 2 bits is enough for storage.
```suggestion
            newType |= (this.getCellType(x) << (2 * x));
```

2024-09-12 16:06 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileChest.java
> +            return (this.type >> (slot * 3)) & 0b111;
Use 2 bits
```suggestion
            return (this.type >> (slot * 2)) & 0b11;
```

2024-09-12 16:06 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileChest.java
> +        this.type = data.readByte() & 0b111;
```suggestion
        this.type = data.readByte() & 0b11;
```

2024-09-12 16:06 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileDrive.java
> +            return (this.type >> (slot * 3)) & 0b111;
```suggestion
            return (this.type >> (slot * 2)) & 0b11;
```

2024-09-12 16:06 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileDrive.java
> +            newType |= ((this.getCellType(x) & 0b111) << (3 * x));
```suggestion
            newType |= ((this.getCellType(x) & 0b11) << (2 * x));
```

2024-09-13 15:07 UTC, OneEyeMaker commented on src/main/java/appeng/tile/storage/TileDrive.java
> +        this.type = data.readInt();
Create variable `oldType` before reading NBT data and compare it with new value in return statement (like it's done in `TileChest:readFromStream_TileChest`).

2024-09-14 07:50 UTC, OneEyeMaker approved these changes

2024-09-14 09:23 UTC, merged

2024-12-08 20:32 UTC, Ethryan commented
I found an issue with this when trying to edit the textures for my texture pack, since they use the same location for both the Drives and the ME Chest, but different sizes its really hard to make a nice texture that fits both. Either it looks really nice in the Drive Bay, and horrible in the ME Chest.
Or the other way around. Any chance we can get the split back so that they use different locations for getting the textures again?