Add fake crafting card for AE
GTNewHorizons/Applied-Energistics-2-Unofficial pull request #622
Opened 2024-12-14 10:41 UTC by MCTBL

https://github.com/user-attachments/assets/a1625364-6fc8-46aa-a6ab-42730abe62de

this upgrade can finish crafting job without receiving output

| item | fake crafting | normal |
| :-: | :-: | :-: |
| ![image](https://github.com/user-attachments/assets/284bf1bd-83ba-4a3c-8b8d-6933ed312e8d) | ![image](https://github.com/user-attachments/assets/997b1e39-a20a-4753-a25e-d5c2ee4771b7) | ![image](https://github.com/user-attachments/assets/b9e851bc-749e-4148-997c-191d319203ab) |

2024-12-18 04:03 UTC, serenibyss commented
Why does this have a button to toggle the mode? Shouldn't an interface having the card enable this functionality, then not having the card is like normal?

2024-12-18 07:17 UTC, miaowwwwww commented
> Why does this have a button to toggle the mode? Shouldn't an interface having the card enable this functionality, then not having the card is like normal?

so that players have the option to not remove the card and to just toggle it off.

2024-12-18 07:18 UTC, MCTBL commented
> Why does this have a button to toggle the mode? Shouldn't an interface having the card enable this functionality, then not having the card is like normal?

I'm not sure if there has any player would use this in some time, so i add it.

2024-12-18 15:10 UTC, serenibyss commented
I don't see why we should add more to the UI when this card is already a toggle on its own

2024-12-21 23:30 UTC, lordIcocain commented on src/main/java/appeng/api/config/Settings.java
> +    FAKE_CRAFTING_MOED(EnumSet.allOf(FakeCraftingMode.class));
MOED

2024-12-21 23:31 UTC, lordIcocain commented on src/main/java/appeng/api/config/Upgrades.java
> +    FAKE_FRAFTING(1);
FRAFTING

2024-12-21 23:47 UTC, lordIcocain commented on src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java
> +                        // if (m instanceof DualityInterface di && di.isFakeCraftingMode()) {
is this redundant?

2024-12-22 03:22 UTC, MCTBL commented on src/main/java/appeng/api/config/Settings.java
> +    FAKE_CRAFTING_MOED(EnumSet.allOf(FakeCraftingMode.class));
sry for my bad english

2024-12-22 08:41 UTC, Dream-Master commented on src/main/java/appeng/api/config/Settings.java
> +    FAKE_CRAFTING_MOED(EnumSet.allOf(FakeCraftingMode.class));
Dont worry my English is not better :)

2024-12-23 17:28 UTC, serenibyss requested changes

2024-12-23 19:29 UTC, merged

2025-06-06 03:36 UTC, MCTBL commented
I wish to re-add the button, Cause tooltips can write description for the fake craft card. To tell the player how to use this card.

2025-06-06 03:42 UTC, AdityaVG13 commented
> I wish to re-add the button, Cause tooltips can write description for the fake craft card. To tell the player how to use this card.

I have already added a quest for this as well